export const SAVE_BILL_REQUEST = "SAVE_BILL_REQUEST";
export const SAVE_BILL_SUCCESS = "SAVE_BILL_SUCCESS";
export const SAVE_BILL_ERROR = "SAVE_BILL_ERROR";
export const SAVE_BILL_RESET = "SAVE_BILL_RESET";

export const UPDATE_BILL_REQUEST = "UPDATE_BILL_REQUEST";
export const UPDATE_BILL_SUCCESS = "UPDATE_BILL_SUCCESS";
export const UPDATE_BILL_ERROR = "UPDATE_BILL_ERROR";
export const UPDATE_BILL_RESET = "UPDATE_BILL_RESET";

export const BILL_LIST_REQUEST = "BILL_LIST_REQUEST";
export const BILL_LIST_SUCCESS = "BILL_LIST_SUCCESS";
export const BILL_LIST_ERROR = "BILL_LIST_ERROR";

export const INSTITUTE_BILL_LIST_REQUEST = "INSTITUTE_BILL_LIST_REQUEST";
export const INSTITUTE_BILL_LIST_SUCCESS = "INSTITUTE_BILL_LIST_SUCCESS";
export const INSTITUTE_BILL_LIST_ERROR = "INSTITUTE_BILL_LIST_ERROR";

export const DELETE_BILL_REQUEST = "DELETE_BILL_REQUEST";
export const DELETE_BILL_SUCCESS = "DELETE_BILL_SUCCESS";
export const DELETE_BILL_ERROR = "DELETE_BILL_ERROR";
export const DELETE_BILL_RESET = "DELETE_BILL_RESET";

export const EDIT_BILL = "EDIT_BILL";
export const EDIT_BILL_RESET = "EDIT_BILL_RESET";

export const PRINT_BILL_DETAILS_REQUEST = "PRINT_BILL_DETAILS_REQUEST";
export const PRINT_BILL_DETAILS_SUCCESS = "PRINT_BILL_DETAILS_SUCCESS";
export const PRINT_BILL_DETAILS_ERROR = "PRINT_BILL_DETAILS_ERROR";
export const PRINT_BILL_DETAILS_RESET = "PRINT_BILL_DETAILS_RESET";

export const FILTER_BILLS_BY_DATE_REQUEST = "FILTER_BILLS_BY_DATE_REQUEST";
export const FILTER_BILLS_BY_DATE_SUCCESS = "FILTER_BILLS_BY_DATE_SUCCESS";
export const FILTER_BILLS_BY_DATE_ERROR = "FILTER_BILLS_BY_DATE_ERROR";
export const FILTER_BILLS_BY_DATE_RESET = "FILTER_BILLS_BY_DATE_RESET";

export const FILTER_BILLS_BY_RANGE_REQUEST = "FILTER_BILLS_BY_RANGE_REQUEST";
export const FILTER_BILLS_BY_RANGE_SUCCESS = "FILTER_BILLS_BY_RANGE_SUCCESS";
export const FILTER_BILLS_BY_RANGE_ERROR = "FILTER_BILLS_BY_RANGE_ERROR";
export const FILTER_BILLS_BY_RANGE_RESET = "FILTER_BILLS_BY_RANGE_RESET";

export const FILTER_INSTITUTE_BILLS_BY_RANGE_REQUEST =
  "FILTER_INSTITUTE_BILLS_BY_RANGE_REQUEST";
export const FILTER_INSTITUTE_BILLS_BY_RANGE_SUCCESS =
  "FILTER_INSTITUTE_BILLS_BY_RANGE_SUCCESS";
export const FILTER_INSTITUTE_BILLS_BY_RANGE_ERROR =
  "FILTER_INSTITUTE_BILLS_BY_RANGE_ERROR";
export const FILTER_INSTITUTE_BILLS_BY_RANGE_RESET =
  "FILTER_INSTITUTE_BILLS_BY_RANGE_RESET";

export const FILTER_INSTITUTE_BILLS_BY_DATE_REQUEST =
  "FILTER_INSTITUTE_BILLS_BY_DATE_REQUEST";
export const FILTER_INSTITUTE_BILLS_BY_DATE_SUCCESS =
  "FILTER_INSTITUTE_BILLS_BY_DATE_SUCCESS";
export const FILTER_INSTITUTE_BILLS_BY_DATE_ERROR =
  "FILTER_INSTITUTE_BILLS_BY_DATE_ERROR";
export const FILTER_INSTITUTE_BILLS_BY_DATE_RESET =
  "FILTER_INSTITUTE_BILLS_BY_DATE_RESET";
