export const UNIT_LIST_REQUEST = "UNIT_LIST_REQUEST";
export const UNIT_LIST_SUCCESS = "UNIT_LIST_SUCCESS";
export const UNIT_LIST_ERROR = "UNIT_LIST_ERROR";

export const UNIT_DETAILS_REQUEST = "UNIT_DETAILS_REQUEST";
export const UNIT_DETAILS_SUCCESS = "UNIT_DETAILS_SUCCESS";
export const UNIT_DETAILS_ERROR = "UNIT_DETAILS_ERROR";

export const ADD_INSTITUTE_REQUEST = "ADD_INSTITUTE_REQUEST";
export const ADD_INSTITUTE_SUCCESS = "ADD_INSTITUTE_SUCCESS";
export const ADD_INSTITUTE_ERROR = "ADD_INSTITUTE_ERROR";
export const ADD_INSTITUTE_RESET = "ADD_INSTITUTE_RESET";

export const EDIT_INSTITUTE_REQUEST = "EDIT_INSTITUTE_REQUEST";
export const EDIT_INSTITUTE_SUCCESS = "EDIT_INSTITUTE_SUCCESS";
export const EDIT_INSTITUTE_ERROR = "EDIT_INSTITUTE_ERROR";
export const EDIT_INSTITUTE_RESET = "EDIT_INSTITUTE_RESET";

export const DELETE_INSTITUTE_REQUEST = "DELETE_INSTITUTE_REQUEST";
export const DELETE_INSTITUTE_SUCCESS = "DELETE_INSTITUTE_SUCCESS";
export const DELETE_INSTITUTE_ERROR = "DELETE_INSTITUTE_ERROR";
export const DELETE_INSTITUTE_RESET = "DELETE_INSTITUTE_ERROR";
